/*
 * TajmerInterrupt.h
 *
 *  Created on: Jan 7, 2026
 *      Author: Andrej
 */

#ifndef LIB_TESTINTERRUPT_TESTINTERRUPTTAJMER_TAJMERINTERRUPT_H_
#define LIB_TESTINTERRUPT_TESTINTERRUPTTAJMER_TAJMERINTERRUPT_H_



#endif /* LIB_TESTINTERRUPT_TESTINTERRUPTTAJMER_TAJMERINTERRUPT_H_ */
